name: Deploy
on:
  workflow_run: # Chaining workflow_run ensures that the Pages deployment doesn't start until the custom build finishes successfully
    workflows: ["Node.js CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      # Does not deploy itself, instead trggers GitHub Pages process.
      # Pages automatically watches for uploaded artifacts
      # Just let it proceed after successful Build
      - name: Trigger GitHub Pages Deployment
        run: echo "Build Successful - GitHub Pages will now deploy automatically"