# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "development" ]

jobs:
  build:

    runs-on: ubuntu-latest
    # container: node:22 # This might help the `act` command run faster, and possibly ensure that it uses the correct container for the Node version

    # strategy:
      # matrix:
        # node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          node-version: ${{ matrix.node-version || '' }} # When no node-version is specified within node-versions, then GitHub will use .nvmrc
          cache: 'npm'

      - uses: actions/configure-pages@v5
      
      - run: node --version && npm --version # Check the expected correct node and npm versions are used
      - run: npm ci --prefix ./App/svgem-react
      - run: npm run build --if-present

      # Upload artifact for GitHub Pages
      - name: Upload artifact for Pages
        # will not attempt to upload to GitHub Pages if `act` command is used locally, which sets env.ACT, but remotely resolves to ''
        if: ${{ !env.ACT }}
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4